// Builds the single-file copy used by Supabase's dashboard editor. No secrets.
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'../supabase');
const handler=fs.readFileSync(path.join(root,'functions/create-staff/handler.ts'),'utf8');
const entry=fs.readFileSync(path.join(root,'functions/create-staff/index.ts'),'utf8')
  .replace("import { makeHandler } from './handler.ts';",'');
fs.writeFileSync(path.join(root,'dashboard-create-staff.ts'),'// Generated by scripts/build-edge.cjs; do not edit this copy.\n'+handler+'\n'+entry);
