const {PGlite}=require('@electric-sql/pglite');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create schema auth;create table auth.users(id uuid primary key,email text,deleted_at timestamptz,banned_until timestamptz);
 create table auth.sessions(id uuid primary key,user_id uuid);
 create function auth.uid() returns uuid language sql stable as $$ select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid $$;
 create function auth.jwt() returns jsonb language sql stable as $$ select nullif(current_setting('request.jwt.claims',true),'')::jsonb $$;
 grant usage on schema auth to authenticated,anon;
 grant execute on function auth.uid(),auth.jwt() to authenticated,anon;`);
 const sql=name=>fs.readFileSync(path.join(__dirname,'../database',name),'utf8');
 // 001 is used ONLY to construct a disposable test database, never rerun in production.
 await db.exec(sql('001_store.sql'));
 const old=crypto.randomUUID(),admin=crypto.randomUUID(),employee=crypto.randomUUID(),session=crypto.randomUUID();
 await db.query("insert into auth.users(id,email) values($1,'old@example.test'),($2,'tamim@users.wj.invalid'),($3,'employee@users.wj.invalid')",[old,admin,employee]);
 await db.query("insert into public.staff_profiles(user_id,display_name,role) values($1,'موظف موجود','employee')",[old]);
 await db.exec(sql('002_username_auth.sql'));
 const previous=(await db.query('select * from public.staff_profiles where user_id=$1',[old])).rows[0];
 assert.equal(previous.display_name,'موظف موجود');assert.equal(previous.role,'employee');assert.equal(previous.username,null);
 await db.exec(sql('first_admin.sql'));
 const first=(await db.query('select * from public.staff_profiles where user_id=$1',[admin])).rows[0];
 assert.equal(first.username,'tamim');assert.equal(first.role,'admin');
 await assert.rejects(()=>db.exec(sql('first_admin.sql')));
 await db.query('insert into auth.sessions values($1,$2)',[session,admin]);
 const provision='select public.provision_staff_username($1,$2,$3,$4,$5,$6)';
 const args=[admin,session,employee,' EmPloyee ','موظف','employee'];
 await db.exec('set role authenticated');await assert.rejects(()=>db.query(provision,args));
 await assert.rejects(()=>db.query("update public.staff_profiles set username='hacked'"));
 await db.exec('reset role; set role anon');await assert.rejects(()=>db.query(provision,args));
 await db.exec('reset role; set role service_role');await db.query(provision,args);
 await db.exec('reset role');assert.equal((await db.query('select username from public.staff_profiles where user_id=$1',[employee])).rows[0].username,'employee');
 const duplicate=crypto.randomUUID();await db.query("insert into auth.users(id,email) values($1,'employee@users.wj.invalid')",[duplicate]);
 await assert.rejects(()=>db.query(provision,[admin,session,duplicate,'EMPLOYEE','Duplicate','employee']));
 await assert.rejects(()=>db.query(provision,[employee,session,duplicate,'newuser','New','admin']));
 await assert.rejects(()=>db.query(provision,[admin,session,old,'wrong','Wrong','employee']));
 await db.query('update public.staff_profiles set active=false where user_id=$1',[admin]);await assert.rejects(()=>db.query(provision,[admin,session,old,'olduser','Old','employee']));
 await db.query('update public.staff_profiles set active=true where user_id=$1',[admin]);
 await db.query('delete from auth.sessions where id=$1',[session]);await assert.rejects(()=>db.query(provision,[admin,session,old,'olduser','Old','employee']));
 assert.equal((await db.query("select count(*)::int n from pg_policies where schemaname='public'")).rows[0].n,5);
 console.log('Username migration, first Admin bootstrap, preserved data/RLS, uniqueness, mapping, provisioning permissions and revocation checks passed.');await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
